FROM python:3.10-slim

# Set the working directory
WORKDIR /app

COPY . /app

# Install packages
RUN pip install requests pandas

# Make output directory exists in the container
RUN mkdir -p /app/data

# Run the Python script
CMD ["python", "script.py"]
